import type { Metadata } from "next"
import { Poppins } from "next/font/google"

import "./globals.css"

import { SidebarProvider } from "./_components/ui/sidebar"

import Header from "./_components/header"
import Footer from "./_components/footer"

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br">
      <body className={`${poppins.className} dark antialiased`}>
        <SidebarProvider>
          <Header />
          <main className="h-full w-dvw">{children}</main>
          <Footer />
        </SidebarProvider>
      </body>
    </html>
  )
}
